apiVersion: v1
kind: Service
metadata:
  name: leaf-server-svc
  namespace: leaf-prd
  labels:
    app: leaf-server-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      name: leaf-server-80
  selector:
    app: leaf-server