apiVersion: v1
kind: ConfigMap
metadata:
  name: leaf-server-cm
  namespace:  leaf-prd
data:
  application.yaml: |
    cors:
      # 建议修改为前端地址(格式：http://example.com)
      allow_origin: '*'
    file:
      max_img_size: 5
      max_video_size: 500
      # 是否兼容IOS下视频播放（如果true，在IPhone中会使用mp4视频）
      video_adaptation_ios: false
    log:
      filename: ./logs/app.log
      max-age: 30
      max-backups: 60
      max-size: 200
      mode: prod
    mail:
      addresser: 网站管理员
      debug: false
      host: smtp.163.com
      # 邮箱秘钥(申请smtp得到的秘钥，不是邮箱密码)
      pass:
      port: 465
      # 发送的邮箱(xxx@xxx.xxx)
      user:
    mongo:
      datasource: leaf
      host: mongodb
      param: authSource=admin
      # mongodb密码（修改要同时修改docker-compose.yml中对应的密码）
      password: LeafMongo123
      port: 27017
      username: root
    mysql:
      datasource: leaf
      host: mysql
      param: charset=utf8mb4&parseTime=True&loc=Local
      # mysql密码（修改要同时修改docker-compose.yml中对应的密码）
      password: LeafRoot123
      port: 3306
      username: root
    oss:
      # oss类型(local服务器存储，aliyun阿里云，tencent腾讯云，qiniu七牛云)
      type: local
      # oss非local类型必填，对应阿里云access_key_id、腾讯云secret_id，七牛云accessKey
      key_id:
      # oss非local类型必填，对应阿里云access_key_secret、腾讯云secret_key，七牛云secretKey
      key_secret:
      # oss非local类型必填
      bucket:
      # 阿里云oss必填，其他不用填写
      endpoint:
      # 腾讯云oss必填，其他不用填写
      app_id:
      # 腾讯云oss必填，其他不用填写
      region:
      # oss自定义域名，七牛云必填，其他根据需求填写，使用local类型此项无效
      domain:
      # oss是否为私有，仅七牛云有效
      private: false
    redis:
      host: redis
      # redis密码（修改要同时修改docker-compose.yml中对应的密码）
      password: LeafRedis123
      port: 6379
    security:
      jwt_secret:
    user:
      prefix: user_
