apiVersion: v1
kind: PersistentVolume
metadata:
  name: leaf-server-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: 文件系统id::接入id

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: leaf-prd
  name: leaf-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi

